### ISSUE TITLE
firemode.name not necessarily the best choice for proplist access

### ISSUE THREAD

**Issue by Armag3ddon** [gitMarky/Library_Shooter#1]
https://github.com/gitMarky/Library_Shooter/blob/refactor/LibraryShooter.ocd/Libraries.ocd/Firearm.ocd/Script.c#L928

shot_counter does get references by firemode.name - since firemode.name is most likely a localised string, that's a desync bound to happen.
I also fear that the fire mode name isn't very unique. Looking at CMC where fire modes are called "Bullets". I guess more than one weapon will fire bullets.

**Comment by gitMarky** [comment]
Yes, I think so, too. The selection by index was not there in the beginning, so the name seemed logical to me. Yes, index is better, or an internal number ID (but this would be the same mess as player number vs. player index, and we already have the fire mode index functions). Feel free to change it :)

**Comment by gitMarky** [comment]
Should be fixed now :)
